name: 'Bootstrap LensKit Conda Environment'
description: 'Bootstraps a Conda-based build environment for LensKit CI.'
inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.9'
  activate-environment:
    description: 'Create and activate the specified Conda environment name'
    required: true
    default: lktest
  blas-implementation:
    description: 'BLAS implementation to activate'
    required: false
  extras:
    description: 'Extras to include in the Conda environment, in addition to dev dependencies'
    required: false
  mixin:
    description: 'A mixin YAML file to include in the environment'
    required: false
  cache-number:
    description: 'Extra cache key for Conda download cache, increment to reset cache.'
    required: false
    default: '0'
  conda-type:
    description: 'The type of Anaconda installation to use for final provisioning'
    required: false
    default: conda
  lock-file-type:
    description: 'The type of environment lock file to create (explicit or yml)'
    required: false
    default: explicit
outputs:
  environment-file:
    description: "The environment file created by the lock stage"
    value: ${{ steps.conda-lock.outputs.environment-file }}
runs:
  using: "composite"
  steps:
    - name: Create bootstrap environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ steps.info.outputs.lock-file }}
        environment-name: lkboot
        cache-downloads: true
        init-shell: none

    - name: Install current build tools
      shell: bash
      run: |
        eval "$(micromamba shell activate -s bash lkboot)"
        python -m pip install git+https://github.com/lenskit/lkbuild.git

    - name: Prepare Conda environment spec
      id: conda-lock
      shell: bash
      run: |
        eval "$(micromamba shell activate -s bash lkboot)"
        e_opts=
        if [ -n "$BLAS_IMPL" ]; then
          e_opts="$e_opts -b $BLAS_IMPL"
        fi
        if [ -n "$EXTRAS" ]; then
          for extra in $(echo "$EXTRAS" |sed -e 's/,/ /g'); do
            e_opts="$e_opts -e $extra"
          done
        fi

        if [ -n "${{inputs.mixin}}" ]; then
          e_opts="$e_opts -m ${{inputs.mixin}}"
        fi

        if [ "$LF_TYPE" = yml ]; then
          e_opts="$e_opts --env-file"
        fi

        echo "extra options: $e_opts"
        lkbuild dev-lock -v $PYVER $e_opts
      env:
        EXTRAS: ${{ inputs.extras }}
        PYVER: ${{ inputs.python-version }}
        BLAS_IMPL: ${{ inputs.blas-implementation }}
        LF_TYPE: ${{ inputs.lock-file-type }}

    - name: ⚒ Initialize Conda environment
      id: conda-init
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: ${{ inputs.activate-environment }}
        environment-file: ${{steps.conda-lock.outputs.environment-file}}
        cache-downloads: true
        init-shell: >-
          bash
          powershell
