name: 'Report Test Results'
description: 'Processes previously-saved test results and reports them.'
runs:
  using: "composite"
  steps:

  - uses: actions/download-artifact@v3
    with:
      path: test-logs

  - name: List log files
    shell: bash
    run: ls -lR test-logs

  - name: Upload coverage
    uses: codecov/codecov-action@v3
    with:
      directory: test-logs/

  - name: Upload all test data
    uses: actions/upload-artifact@v1
    with:
      name: test-outputs
      path: test-logs
