name: 'Bootstrap LensKit Build Environment'
description: 'Bootstraps a Conda-based buil environment for LensKit CI.'
inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.9'
  activate-environment:
    description: 'Create and activate the specified Conda environment name'
    required: true
    default: lktest
  blas-implementation:
    description: 'BLAS implementation to activate'
    required: false
  extras:
    description: 'Extras to include in the Conda environment, in addition to dev dependencies'
    required: false
outputs:
  environment-file:
    description: "The environment file created by the lock stage"
    value: ${{ steps.conda-lock.outputs.environment-file }}
runs:
  using: "composite"
  steps:
    - name: Copy bootstrap environment
      shell: bash
      run: |
        ls "$ACTPATH/../.."
        cp -v "$ACTPATH/../../boot-env.yml" boot-env.yml
      env:
        ACTPATH: ${{ github.action_path }}

    - name: Backup bashrc
      shell: bash
      run: |
        if [ -f "$HOME/.bash_profile" ]; then
          cp $HOME/.bash_profile $HOME/.bash_profile.premm
        fi

    - name: 👢 Create bootstrap environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: lkboot
        environment-file: boot-env.yml

    - name: 🔒 Prepare Conda environment spec
      id: conda-lock
      shell: bash -l {0}
      run: |
        e_opts=
        if [ -n "$BLAS_IMPL" ]; then
          e_opts="$e_opts -b $BLAS_IMPL"
        fi
        if [ -n "$EXTRAS" ]; then
          for extra in $(echo "$EXTRAS" |sed -e 's/,/ /'); do
            e_opts="$e_opts -e $extra"
          done
        fi
        lkbuild dev-lock -v $PYVER $e_opts --gh-set-output
      env:
        EXTRAS: ${{ inputs.extras }}
        PYVER: ${{ inputs.python-version }}
        BLAS_IMPL: ${{ inputs.blas-implementation }}

    - name: Restore bashrc
      shell: bash
      run: |
        if [ -f "$HOME/.bash_profile.premm" ]; then
          mv $HOME/.bash_profile.premm $HOME/.bash_profile
        else
          rm "$HOME/.bash_profile"
        fi

    - name: ⚒ Initialize Conda
      id: conda-init
      uses: conda-incubator/setup-miniconda@v2
      if: inputs.activate-environment
      with:
        activate-environment: ${{ inputs.activate-environment }}
        environment-file: ${{steps.conda-lock.outputs.environment-file}}
