name: 'Bootstrap LensKit Build Environment'
description: 'Bootstraps a Conda-based buil environment for LensKit CI.'
inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.9'
  activate-environment:
    description: 'Create and activate the specified Conda environment name'
    required: true
    default: lktest
outputs:
  environment-file:
    description: "The environment file created by the lock stage"
    value: ${{ steps.conda-lock.outputs.environment-file }}
runs:
  using: "composite"
  steps:
    - name: debug
      shell: bash
      run: ls ${{ github.action_path }}/../..

    - name: 👢 Create bootstrap environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: lkboot
        environment-file: ${{ github.action_path }}/../../boot-env.yml

    - name: 🔒 Prepare Conda environment spec
      id: conda-lock
      shell: bash
      run: |
        conda run -n lkboot --no-capture-output lkbuild dev-lock -v $PYVER --gh-set-output
      env:
        PYVER: ${{ inputs.python-version }}

    - name: ⚒ Initialize Conda
      id: conda-init
      uses: conda-incubator/setup-miniconda@v2
      if: inputs.activate-environment
      with:
        activate-environment: ${{ inputs.activate-environment }}
        environment-file: ${{steps.conda-lock.outputs.environment-file}}
