name: 'Bootstrap LensKit Vanilla Environment'
description: 'Bootstraps a vanilla Python build environment for LensKit CI.'

inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.9'

  extras:
    description: 'Extras to include in the installed dependencies, in addition to dev dependencies'
    required: false

  include-dev-dependencies:
    description: 'Include the development dependencies (dev & test extras)'
    required: false
    default: true

  constraints-file:
    description: "Constraints file for Pip resolution"
    required: false

  install-package:
    description: 'Install the package and its dependencies (on by default)'
    required: false
    default: true

  preinstall-helpers:
    description: 'Install lenskit-build-helpersf rom Git'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: x64

    - name: Set up Python build deps
      shell: bash
      env:
        PIP_PREFER_BINARY: 'true'
      run: |
        python -m pip install -U flit wheel

    - name: Preinstalling LensKit build helpers from Git
      if: inputs.preinstall-helpers
      shell: bash
      run: |
        python -m pip install git+https://github.com/lenskit/lkbuild.git

    - name: Install package and dependencies
      if: inputs.install-package
      shell: bash
      env:
        PIP_PREFER_BINARY: 'true'
      run: |
        if [ X"${{inputs.include-dev-dependencies}}" = Xtrue ]; then
          extras="test,dev"
        else
          extras=""
        fi
        for e in $(echo "${{inputs.extras}}" | sed -e 's/,/ /'); do
          if [ -z "$extras" ]; then
            extras="$e"
          else
            extras="$extras,$e"
          fi
        done
        opts=""
        if [ -n "${{inputs.constraints-file}}" ]; then
          opts="$opts -c ${{inputs.constraints-file}}"
        fi
        echo "installing with extras $extras"
        python -m pip install $opts ".[$extras]"
